export const categories = [
  { id: 1, name: "Sıcak İçecekler" },
  { id: 2, name: "Soğuk İçecekler" },
  { id: 3, name: "Tatlılar" }
]

export const items = [
 { id: 1,
     categoryId: 1,
      name: "Espresso",
       description: "Yoğun tek shot",
        image: "/items/espresso.jpg",
         price: 60, 
         available: true },

{ id: 2,
     categoryId: 1,
      name: "Latte",
       description: "Süt + espresso",
        image: "/items/latte.jpg",
         price: 75, 
         available: true },

{ id: 3,
     categoryId: 1,
      name: "Americano",
       description: "Yumuşak içim",
        image: "/items/americano.jpg",
         price: 70, 
         available: true },

{ id: 4,
     categoryId: 1,
      name: "Cappuccino",
       description: "Bol süt köpüğü",
        image: "/items/cappuccino.jpg",
         price: 80, 
         available: true },

{ id: 5,
     categoryId: 1,
      name: "Mocha",
       description: "Çikolatalı kahve",
        image: "/items/mocha.jpg",
         price: 90, 
         available: true },

{ id: 6,
     categoryId: 2,
      name: "Iced Filter Coffee",
       description: "Soğuk filtre kahve",
        image: "/items/ice-filter.jpg",
         price: 65, 
         available: true },

{ id: 7,
     categoryId: 2,
      name: "Ice Latte",
       description: "Soğuk süt + espresso",
        image: "/items/ice-latte.jpg",
         price: 85, 
         available: true },

{ id: 8,
     categoryId: 2,
      name: "Ice Americano",
       description: "Soğuk filtre kahve tarzı",
        image: "/items/ice-americano.jpg",
         price: 75, 
         available: true },

{ id: 9,
     categoryId: 2,
      name: "Ice Cappuccino",
      description: "Soğuk köpüklü latte",
      image: "/items/ice-cappuccino.jpg",
       price: 90, 
       available: true },

{ id: 10,
     categoryId: 2,
      name: "Ice Mocha",
       description: "Çikolatalı soğuk kahve",
        image: "/items/ice-mocha.jpg",
         price: 95, 
         available: true },

{ id: 11,
     categoryId: 3,
      name: "Cheesecake",
       description: "New York usulü",
        image: "/items/cheesecake.jpg",
         price: 110, 
         available: true },

{ id: 12,
     categoryId: 3, 
     name: "Brownie",
      description: "Yoğun çikolatalı",
       image: "/items/brownie.jpg",
        price: 95,
         available: true },

{ id: 13,
     categoryId: 3,
      name: "Tiramisu",
       description: "İtalyan klasiği",
        image: "/items/tiramisu.jpg",
         price: 120,
          available: true },

{ id: 14,
     categoryId: 3,
      name: "San Sebastian",
       description: "Yanık cheesecake",
        image: "/items/san-sebastian.jpg",
         price: 130,
          available: true },

{ id: 15,
     categoryId: 3,
      name: "Magnolia",
       description: "Bisküvili çilekli tatlı",
        image: "/items/magnolia.jpg",
         price: 105,
          available: true },


]
